services:
  app:
    build:
      context: /home/ubuntu/apps/real-time-fund
      args:
        NEXT_PUBLIC_SUPABASE_URL: https://runtime-replace.supabase.co
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        NEXT_PUBLIC_WEB3FORMS_ACCESS_KEY: ${NEXT_PUBLIC_WEB3FORMS_ACCESS_KEY}
        NEXT_PUBLIC_GA_ID: ${NEXT_PUBLIC_GA_ID}
        NEXT_PUBLIC_GITHUB_LATEST_RELEASE_URL: ${NEXT_PUBLIC_GITHUB_LATEST_RELEASE_URL}
        NEXT_PUBLIC_IS_GITHUB_LOGIN: ${NEXT_PUBLIC_IS_GITHUB_LOGIN}
    env_file:
      - /home/ubuntu/apps/real-time-fund/.env
    network_mode: host
    restart: always
    environment:
      NODE_ENV: production
