import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
import { createClient } from 'jsr:@supabase/supabase-js@2';
console.info('get-fund-valuation-trend server started');
const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const SUPABASE_ANON_KEY = Deno.env.get('SUPABASE_ANON_KEY')!;
const corsHeaders = { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type' };
interface ValuationRow { gztime: string; gszzl: number; source: string; }
const RANGE_DAYS: Record<string, number> = {'1m':31,'3m':93,'6m':183,'1y':365,'3y':1095,'all':1825};
function getDays(r: string): number { return RANGE_DAYS[r] ?? 93; }
async function fetchQdii(supabase: any, code: string, range: string): Promise<ValuationRow[]> { try { const days = getDays(range); const since = new Date(); since.setDate(since.getDate() - days); const { data, error } = await supabase.from('gs_qdii').select('dwjz,gztime').eq('fund_code', code).gte('gztime', since.toISOString().slice(0,10)).order('gztime', { ascending: true }); if (error || !data || data.length < 2) return []; const r: ValuationRow[] = []; for (let i = 1; i < data.length; i++) { const prev = Number(data[i-1].dwjz), curr = Number(data[i].dwjz); if (!Number.isFinite(prev) || !Number.isFinite(curr) || prev===0) continue; r.push({ gztime: data[i].gztime, gszzl: ((curr-prev)/prev)*100, source: 'supabase_qdii' }); } return r; } catch(e) { return []; } }
async function fetchSina(code: string, range: string): Promise<ValuationRow[]> { try { const days = getDays(range); const since = new Date(); since.setDate(since.getDate() - days); const sinceStr = since.toISOString().slice(0,10); const url = 'https://stock.finance.sina.com.cn/fundInfo/api/openapi.php/FdFundService.getEstimateNetworthPic?symbol=' + code; const resp = await fetch(url, { headers: { 'User-Agent': 'Mozilla/5.0' }, signal: AbortSignal.timeout(10000) }); if (!resp.ok) return []; const text = await resp.text(); const m = text.match(/jsonp_sina_[0-9]+_[0-9]+\(([^)]+)\)/); if (!m) return []; const json = JSON.parse(m[1]); const nw: any[] = json?.result?.data?.networth || []; if (!nw.length) return []; const filtered = nw.filter((p: any) => p.pre_date >= sinceStr); const r2: ValuationRow[] = [], r3: ValuationRow[] = []; for (let i = 1; i < filtered.length; i++) { const pPrev = Number(filtered[i-1].pre_nav), pCurr = Number(filtered[i].pre_nav); if (Number.isFinite(pPrev) && Number.isFinite(pCurr) && pPrev !== 0) r2.push({ gztime: filtered[i].pre_date, gszzl: ((pCurr-pPrev)/pPrev)*100, source: 'sina_ds2' }); const p2Prev = Number(filtered[i-1].pre_nav2), p2Curr = Number(filtered[i].pre_nav2); if (Number.isFinite(p2Prev) && Number.isFinite(p2Curr) && p2Prev !== 0) r3.push({ gztime: filtered[i].pre_date, gszzl: ((p2Curr-p2Prev)/p2Prev)*100, source: 'sina_ds3' }); } return [...r2, ...r3]; } catch(e) { return []; } }
async function fetchEastmoney(code: string, range: string): Promise<ValuationRow[]> { try { const days = getDays(range); const since = new Date(); since.setDate(since.getDate() - days); const url = 'https://api.fund.eastmoney.com/f10/lsjz?callback=jQuery&fundCode=' + code + '&pageIndex=1&pageSize=300&startDate=' + since.toISOString().slice(0,10) + '&endDate=' + new Date().toISOString().slice(0,10); const resp = await fetch(url, { headers: { 'User-Agent': 'Mozilla/5.0', 'Referer': 'https://fund.eastmoney.com/' }, signal: AbortSignal.timeout(10000) }); if (!resp.ok) return []; const text = await resp.text(); const json = JSON.parse(text.replace(/^jQuery\(/, '').replace(/\)$/, '')); const rows: any[] = json?.Data?.LSJZList || []; if (!rows.length) return []; const r: ValuationRow[] = []; for (let i = 1; i < rows.length; i++) { const prev = Number(rows[i-1].DWJZ), curr = Number(rows[i].DWJZ); if (!Number.isFinite(prev) || !Number.isFinite(curr) || prev === 0) continue; r.push({ gztime: rows[i].FSRQ, gszzl: ((curr-prev)/prev)*100, source: 'fundgz' }); } return r; } catch(e) { return []; } }
Deno.serve(async (req) => { if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders }); try { const auth = req.headers.get('Authorization'); if (!auth) return new Response(JSON.stringify({error:'Unauthorized'}), {status:401, headers:{...corsHeaders,'Content-Type':'application/json'}}); const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, { global: { headers: { Authorization: auth } } }); const { data: { user } } = await supabase.auth.getUser(); if (!user) return new Response(JSON.stringify({error:'Unauthorized'}), {status:401, headers:{...corsHeaders,'Content-Type':'application/json'}}); const body = await req.json().catch(() => ({})); const code = String(body.fund_code || '').trim(); const range = body.range || '3m'; if (!code) return new Response(JSON.stringify({error:'fund_code required'}), {status:400, headers:{...corsHeaders,'Content-Type':'application/json'}}); const [qdii, sina, em] = await Promise.all([fetchQdii(supabase, code, range), fetchSina(code, range), fetchEastmoney(code, range)]); return new Response(JSON.stringify({data: [...qdii, ...sina, ...em]}), {status:200, headers:{...corsHeaders,'Content-Type':'application/json'}}); } catch(err: any) { return new Response(JSON.stringify({error: err.message}), {status:500, headers:{...corsHeaders,'Content-Type':'application/json'}}); } });
